# О Numpy

NumPy — это библиотека языка Python, добавляющая поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых (и очень быстрых) математических функций для операций с этими массивами. 

Numpy - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.


## Что является основным объеком numpy?

Основным объектом NumPy является однородный многомерный массив. Это многомерный массив элементов (обычно чисел), одного типа.

Здесь можно подчеркнуть одного типа. Эта существенная деталь позволяет заметно ускорить работу с такими объектами. Зная, что данный объект имеет только, скажем, целые числа, то не будут производится проверки типов. Плюс к этому - уменьшается общий объем памяти для хранения таких объектов.

dtype
size
ndim
shape
itemsize
data

## Создание массивов

In [1]:
import numpy as np

В NumPy существует много способов создать массив. Один из наиболее простых - создать массив из обычных списков или кортежей Python, используя функцию numpy.array() (запомните: array - функция, создающая объект типа ndarray):

In [2]:
a = np.array([1, 2, 3])
print (a)
type(a)

[1 2 3]


numpy.ndarray

In [3]:
a.shape

(3,)

Функция array() трансформирует вложенные последовательности в многомерные массивы. Тип элементов массива зависит от типа элементов исходной последовательности (но можно и переопределить его в момент создания).

In [4]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Функция zeros() создает массив из нулей, а функция ones() — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype

In [8]:
print (np.zeros((3, 5)))
print (np.ones((2, 2)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


Функция eye() создаёт единичную матрицу (двумерный массив)

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Функция empty() создает массив без его заполнения. Исходное содержимое случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится):

In [10]:
np.empty((3, 3))

array([[0.00000000e+000, 2.45056560e-321, 2.47032823e-323],
       [9.71701984e-312, 0.00000000e+000, 2.47032823e-323],
       [9.71701027e-312, 0.00000000e+000, 3.23815565e-319]])

Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), только вместо списков она возвращает массивы, и принимает не только целые значения:

In [11]:
print (np.arange(10, 30, 5))
print (np.arange(0, 1, 0.1))

[10 15 20 25]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Функция linspace() вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов:

In [12]:
np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Базовые операции

In [13]:
a = np.array([20, 30, 40, 50])

In [14]:
a.ndim #кол-во размерностей

1

In [15]:
a.shape #размер каждой размерности

(4,)

In [16]:
a.size #кол-во элементов в матрице

4

In [17]:
a.dtype #тип массива

dtype('int32')

In [18]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [24]:
b/b

C:\Users\VLADIMIR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.])

In [19]:
a + b

array([20, 31, 42, 53])

In [20]:
a - b

array([20, 29, 38, 47])

In [21]:
a * b

array([  0,  30,  80, 150])

In [22]:
a / b  # При делении на 0 возвращается inf (бесконечность)

C:\Users\VLADIMIR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 30.        , 20.        , 16.66666667])

In [25]:
a ** b

array([     1,     30,   1600, 125000], dtype=int32)

In [26]:
a % b  # При взятии остатка от деления на 0 возвращается 0

C:\Users\VLADIMIR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 2], dtype=int32)

Для этого, естественно, массивы должны быть одинаковых размеров.

In [27]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
c.shape

(2, 3)

In [28]:
d = np.array([[1, 2], [3, 4], [5, 6]])

In [30]:
d.shape

(3, 2)

In [31]:
c + d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Также можно производить математические операции между массивом и числом. В этом случае к каждому элементу прибавляется (или что вы там делаете) это число.

In [32]:
a

array([20, 30, 40, 50])

In [33]:
a + 1

array([21, 31, 41, 51])

In [34]:
a ** 3

array([  8000,  27000,  64000, 125000], dtype=int32)

In [39]:
a[a < 35)]  # И фильтрацию можно проводить

array([40, 50])

NumPy также предоставляет множество математических операций для обработки массивов:

In [40]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [41]:
np.arctan(a)

array([1.52083793, 1.53747533, 1.54580153, 1.55079899])

Многие унарные операции, такие как, например, вычисление суммы всех элементов массива, представлены также и в виде методов класса ndarray.

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
a.sum(axis = 1)

array([ 6, 15])

In [48]:
a.min(axis = 0)

array([1, 2, 3])

In [49]:
a.max()

6

По умолчанию, эти операции применяются к массиву, как если бы он был списком чисел, независимо от его формы. Однако, указав параметр axis, можно применить операцию для указанной оси массива:

In [ ]:
a.min(axis=0)  # Наименьшее число в каждом столбце

In [ ]:
a.min(axis=1)  # Наименьшее число в каждой строке

In [50]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
b.reshape(3,-1) # 2d array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Индексы, срезы, итерации

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

In [54]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [55]:
a[1]

1

In [56]:
a[3:7]

array([ 27,  64, 125, 216], dtype=int32)

In [57]:
a[3:7] = 8
a

array([  0,   1,   8,   8,   8,   8,   8, 343, 512, 729], dtype=int32)

In [58]:
# В обратном порядке
a[::-1]

array([729, 512, 343,   8,   8,   8,   8,   8,   1,   0], dtype=int32)

У многомерных массивов на каждую ось приходится один индекс. Индексы передаются в виде последовательности чисел, разделенных запятыми (то бишь, кортежами):

In [59]:
b = np.array([[  0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [60]:
b[2,3]

23

In [61]:
b[:,2]  # Третий столбец

array([ 2, 12, 22, 32, 42])

In [64]:
b[:2]  # Первые две строки

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [65]:
b[1:3, : : ]  # Вторая и третья строки

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [66]:
b[-1] # последняя строка

array([40, 41, 42, 43])

In [98]:
for row in b:
    print(row)

[5 6]
[7 8]


In [69]:
for el in b.flat:
    print(el)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Манипуляции с формой

Как уже говорилось, у массива есть форма (shape), определяемая числом элементов вдоль каждой оси:

In [70]:
a = np.array([[  0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [71]:
a.shape

(5, 4)

Форма массива может быть изменена с помощью различных команд:

In [72]:
a.ravel()  # Делает массив плоским

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [73]:
a.shape = (4, 5)  # Изменение формы
a

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [74]:
a.reshape((-1, 4))  # Изменение формы
#a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

Метод reshape() возвращает ее аргумент с измененной формой - это функция, в то время как метод resize() изменяет сам массив - это процедура:

## Объединение массивов

Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.

hstack() объединяет массивы по первым осям, vstack() — по последним:

In [75]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [76]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [77]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Random

In [79]:
np.random.random(10)

array([0.30347707, 0.58688703, 0.70149673, 0.72003399, 0.85329173,
       0.45082398, 0.17912536, 0.30303733, 0.65765469, 0.33397824])

In [82]:
np.random.randint(0, 3, (3,10))

array([[0, 0, 1, 2, 2, 2, 0, 0, 1, 1],
       [1, 2, 1, 1, 1, 1, 1, 1, 2, 0],
       [1, 0, 0, 0, 2, 1, 1, 2, 1, 2]])

In [83]:
np.random.uniform(2, 8, (2, 10)) # с различными распределениями (равномерное)

array([[3.06668682, 6.44334006, 3.64910007, 7.51026667, 7.65445458,
        2.25878985, 5.89460098, 3.03370688, 3.47179263, 5.72048675],
       [5.99376639, 2.67722401, 4.4192481 , 3.24197073, 7.06355596,
        3.83094123, 2.74082187, 5.07291973, 2.32251901, 4.35070539]])

## Выбор и перемешивание

In [84]:
a = np.arange(10) # массив от 0 до 9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# Перемешать NumPy массив можно с помощью функции shuffle
np.random.shuffle(a)
a

array([9, 8, 6, 3, 1, 2, 7, 5, 4, 0])

## Практические задачки:

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [ ]:
# Ваш код здесь

Создать вектор размера 10, заполненный числом 2.5

In [ ]:
# Ваш код здесь

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [ ]:
# Ваш код здесь

Создать вектор со значениями от 10 до 49

In [ ]:
# Ваш код здесь

Создать трехмерный массив (3, 3, 4) из рандомных чисел и сделать из него двумерный (5,2)

In [ ]:
# Ваш код здесь

Создать массив рандомных данных (6,6). Сумму по строкам поделить на минимумы по соответствующим индексам столбцов. Показать индекс максимального элемента в массиве рандомных данных.

In [ ]:
# Ваш код здесь

## Индексация 

In [87]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x[1:7:2] # start = 1 index, stop = 7-1 index, step = 2

array([1, 3, 5])

In [93]:
x[-2:10] # start=n-2, stop=10-1, step=1

array([8, 9])

In [94]:
x[-7]

3

In [95]:
x[5:]

array([5, 6, 7, 8, 9])

Сложная индексация:

In [96]:
x[x>4]

array([5, 6, 7, 8, 9])

In [97]:
x>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])