# О Numpy

NumPy — это библиотека языка Python, добавляющая поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых (и очень быстрых) математических функций для операций с этими массивами. 

Numpy - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.


## Что является основным объеком numpy?

Основным объектом NumPy является однородный многомерный массив. Это многомерный массив элементов (обычно чисел), одного типа.

Здесь можно подчеркнуть одного типа. Эта существенная деталь позволяет заметно ускорить работу с такими объектами. Зная, что данный объект имеет только, скажем, целые числа, то не будут производится проверки типов. Плюс к этому - уменьшается общий объем памяти для хранения таких объектов.

dtype
size
ndim
shape
itemsize
data

## Создание массивов

In [1]:
import numpy as np

В NumPy существует много способов создать массив. Один из наиболее простых - создать массив из обычных списков или кортежей Python, используя функцию numpy.array() (запомните: array - функция, создающая объект типа ndarray):

In [26]:
a = np.array([1, 2, 3])
print (a)
type(a)

[1 2 3]


numpy.ndarray

Функция array() трансформирует вложенные последовательности в многомерные массивы. Тип элементов массива зависит от типа элементов исходной последовательности (но можно и переопределить его в момент создания).

In [107]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [108]:
b.shape

(2, 3)

In [28]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

Функция zeros() создает массив из нулей, а функция ones() — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype

In [90]:
a

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [29]:
print (np.zeros((3, 5)))
print (np.ones((2, 2)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [87]:
print (np.zeros((4, 5, 6)))

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


Функция eye() создаёт единичную матрицу (двумерный массив)

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Функция empty() создает массив без его заполнения. Исходное содержимое случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится):

In [31]:
np.empty((3, 3))

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), только вместо списков она возвращает массивы, и принимает не только целые значения:

In [32]:
print (np.arange(10, 30, 5))
print (np.arange(0, 1, 0.1))

[10 15 20 25]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Функция linspace() вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов:

In [33]:
np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
##########Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Базовые операции

In [3]:
a = np.array([20, 30, 40, 50])

In [35]:
a.ndim #кол-во размерностей

1

In [36]:
a.shape #размер каждой размерности

(4,)

In [37]:
a.size #кол-во элементов в матрице

4

In [38]:
a.dtype #тип массива

dtype('int32')

In [5]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [40]:
a + b

array([20, 31, 42, 53])

In [41]:
a - b

array([20, 29, 38, 47])

In [42]:
a * b

array([  0,  30,  80, 150])

In [43]:
a / b  # При делении на 0 возвращается inf (бесконечность)

C:\Users\VLADIMIR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 30.        , 20.        , 16.66666667])

In [44]:
a ** b

array([     1,     30,   1600, 125000], dtype=int32)

In [6]:
a % b  # При взятии остатка от деления на 0 возвращается 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 2], dtype=int32)

Для этого, естественно, массивы должны быть одинаковых размеров.

In [24]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
d = np.array([[1, 2], [3, 4], [5, 6]])

In [26]:
c + d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Также можно производить математические операции между массивом и числом. В этом случае к каждому элементу прибавляется (или что вы там делаете) это число.

In [49]:
a + 1

array([21, 31, 41, 51])

In [50]:
a ** 3

array([  8000,  27000,  64000, 125000], dtype=int32)

In [51]:
a < 35  # И фильтрацию можно проводить

array([ True,  True, False, False])

In [22]:
#####Задача отобразить элементы больше 30#####
##############################################
a[a>30]

array([40, 50])

In [23]:
for i in a:
    if i > 30:
        print(i)

40
50


NumPy также предоставляет множество математических операций для обработки массивов:

In [52]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [53]:
np.arctan(a)

array([1.52083793, 1.53747533, 1.54580153, 1.55079899])

Многие унарные операции, такие как, например, вычисление суммы всех элементов массива, представлены также и в виде методов класса ndarray.

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [55]:
a.sum()

21

In [56]:
a.min()

1

In [57]:
a.max()

6

По умолчанию, эти операции применяются к массиву, как если бы он был списком чисел, независимо от его формы. Однако, указав параметр axis, можно применить операцию для указанной оси массива:

In [58]:
a.min(axis=0)  # Наименьшее число в каждом столбце

array([1, 2, 3])

In [59]:
a.min(axis=1)  # Наименьшее число в каждой строке

array([1, 4])

In [60]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
b.reshape(4,3) # 2d array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
########### Объяснить что такое NAN. Выяснить результат следующих выражений
0 * np.nan

nan

In [39]:
np.nan == np.nan

False

In [40]:
np.inf > np.nan

False

In [41]:
np.nan - np.nan

nan

In [42]:
0.3 == 3 * 0.1

False

In [43]:
3*0.1

0.30000000000000004

## Индексы, срезы, итерации

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

In [62]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [63]:
a[1]

1

In [64]:
a[3:7]

array([ 27,  64, 125, 216], dtype=int32)

In [65]:
a[3:7] = 8
a

array([  0,   1,   8,   8,   8,   8,   8, 343, 512, 729], dtype=int32)

In [66]:
# В обратном порядке
a[::-1]

array([729, 512, 343,   8,   8,   8,   8,   8,   1,   0], dtype=int32)

У многомерных массивов на каждую ось приходится один индекс. Индексы передаются в виде последовательности чисел, разделенных запятыми (то бишь, кортежами):

In [8]:
b = np.array([[  0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [68]:
b[2,3]

23

In [69]:
b[:,2]  # Третий столбец

array([ 2, 12, 22, 32, 42])

In [70]:
b[:2]  # Первые две строки

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [15]:
b[1:3, : :]  # Вторая и третья строки

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [72]:
b[-1] # последняя строка

array([40, 41, 42, 43])

In [73]:
for row in a:
    print(row)

0
1
8
8
8
8
8
343
512
729


In [47]:
#######Задача на создание матрицы, заполненной в шахматном порядке нулями и единицами 8х8

Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
#####Создать матрицу с 0 внутри, и 1 на границах#####
##############################################
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [80]:
################Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## Манипуляции с формой

Как уже говорилось, у массива есть форма (shape), определяемая числом элементов вдоль каждой оси:

In [75]:
a = np.array([[  0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [76]:
a.shape

(5, 4)

Форма массива может быть изменена с помощью различных команд:

In [77]:
a.ravel()  # Делает массив плоским

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [78]:
a.shape = (4, 5)  # Изменение формы
a

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [79]:
a.reshape((-1, 4))  # Изменение формы
#a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [81]:
######Поменять 2 строки в матрице
##################
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [85]:
#Показать кумулятивную сумму
np.cumsum(a, dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2.],
       [2., 2., 3., 3., 3.],
       [3., 3., 3., 4., 4.],
       [4., 4., 4., 4., 5.]])

Метод reshape() возвращает ее аргумент с измененной формой - это функция, в то время как метод resize() изменяет сам массив - это процедура:

## Объединение массивов

Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.

hstack() объединяет массивы по первым осям, vstack() — по последним:

In [80]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [81]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [82]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [83]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Random

In [84]:
np.random.random(10)

array([0.27303439, 0.03756786, 0.79311855, 0.62128648, 0.02669963,
       0.70119715, 0.92943207, 0.06420841, 0.48561112, 0.17027125])

In [85]:
np.random.randint(0, 3, (3,10))

array([[0, 2, 2, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0, 2, 0, 2, 1, 1],
       [2, 2, 1, 0, 2, 1, 1, 2, 2, 2]])

In [86]:
np.random.uniform(2, 8, (2, 10)) # с различными распределениями (равномерное)

array([[6.63814551, 7.33983714, 3.56363098, 7.04598543, 4.35588614,
        5.913042  , 6.82950552, 5.2133489 , 4.23241809, 3.37392994],
       [2.22726321, 7.17702491, 3.00319049, 4.61914895, 2.83139515,
        6.14711073, 5.93890885, 5.63988459, 4.12568424, 6.5963986 ]])

## Выбор и перемешивание

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# Перемешать NumPy массив можно с помощью функции shuffle
np.random.shuffle(a)
a

array([2, 4, 6, 0, 7, 1, 5, 3, 8, 9])

In [94]:
####################Создать обратно диагональную матрицу

a=np.eye(5)

a[:,::-1]
###################Создать матрицу n на n где на обратных диагоналях находятся одинаковые числа. 
##При приближении к диагонали числа растут на 1, при удалении уменьшаются на 1

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [ ]:
###########Нарисовать условие на доске

In [ ]:
###########Задание
###########Создать матрицу 15х6, где строки состоят из не повторяющихся чисел от 1 до 6.

In [ ]:
###########Задание
###########Создать матрицу 15х6, где в строках есть одна 1 и остальные 0

In [ ]:
#############Перемножить матрицы и получить сумму

## Практические задачки:

In [ ]:
#############Объяснить матричное умножение

In [48]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Создать вектор (одномерный массив) размера 10, заполненный нулями

In [89]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный числом 2.5

In [90]:
Z = np.full(10, 2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [91]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [92]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Создать трехмерный массив (3, 3, 4) из рандомных чисел и сделать из него двумерный (5,2)

In [146]:
a = np.random.random((3,3,4))
a

array([[[0.16925226, 0.65947831, 0.54864521, 0.63661853],
        [0.72550494, 0.86531891, 0.01349376, 0.62111681],
        [0.4612691 , 0.82944218, 0.76943789, 0.91021784]],

       [[0.68394896, 0.91139097, 0.66327254, 0.75812099],
        [0.90162209, 0.46918074, 0.55459664, 0.0570429 ],
        [0.25395978, 0.61100073, 0.89669125, 0.08708615]],

       [[0.58610782, 0.00707211, 0.42438332, 0.28795586],
        [0.41479581, 0.97694323, 0.26583254, 0.02754269],
        [0.00950628, 0.56803779, 0.16018838, 0.77169146]]])

In [148]:
a.resize(5,2) # Метод. Важно, чтобы была та же размерность

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [147]:
np.resize(a, (5,2)) # Функция, берет первые элементы

array([[0.16925226, 0.65947831],
       [0.54864521, 0.63661853],
       [0.72550494, 0.86531891],
       [0.01349376, 0.62111681],
       [0.4612691 , 0.82944218]])

In [126]:
a.resize(5,2)
a

array([[0.75635613, 0.72937603],
       [0.18568243, 0.98202317],
       [0.71655086, 0.99152751],
       [0.93245061, 0.18343789],
       [0.85896839, 0.30572553]])

Создать массив рандомных данных (6,6). Сумму по строкам поделить на минимумы по соответствующим индексам столбцов. Показать индекс максимального элемента в массиве рандомных данных.

In [94]:
a = np.random.random((6,6)) ; 
a.sum(axis=1)/a.min(axis = 0); 

a.argmax()

3

## Индексация 

In [95]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
x[1:7:2] # start = 1 index, stop = 7-1 index, step = 2

array([1, 3, 5])

In [97]:
x[-2:10] # start=n-2, stop=10-1, step=1

array([8, 9])

In [98]:
x[-7]

3

In [99]:
x[5:]

array([5, 6, 7, 8, 9])

Advanced Indexing:

In [100]:
x[x>4]

array([5, 6, 7, 8, 9])

In [101]:
x>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])